### ISSUE TITLE
[Page: Phoneme Timing]

### ISSUE THREAD

**Issue by Robintes** [claire-west/svstudio-manual#16]
**Describe the problem**
<A clear and concise description of the problem. This user manual is unofficial and not affiliated with Dreamtonics, please only report issues with the user manual, not with the SynthV Studio application.>

**Additional context**
<Any other context about the problem here.> what is the significance of the chevron in the top rh corner of a note. this has appeared suddenly. previous examples didnt have this?

**Comment by claire-west** [comment]
It just means the note is in Manual Mode. This was a new visual indicator added with 1.9.0, but the prior screenshots were taken when the indicator did not exist. As for this particular page, the pitch mode of the notes is inconsequential.

I've been planning to add mention of it to the quickstart section, just haven't quite gotten around to it yet.

**Comment by Robintes** [comment]
Thnx Claire Ive copied your reply to the forum, then I found it lurking under "manual pitch mode" in the UUM - stupid boy Pike

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
