### ISSUE TITLE
[Page: MIDI Controller]

### ISSUE THREAD

**Issue by Robintes** [claire-west/svstudio-manual#19]
**Describe the problem**
<A clear and concise description of the problem. This user manual is unofficial and not affiliated with Dreamtonics, please only report issues with the user manual, not with the SynthV Studio application.>

**Additional context**
<Any other context about the problem here.> Does SV support Midi velocity data?  So pressing a key soft and hard makes a difference?
I assume only note value and duration are read when importing a midi song file and no other expression (ASDR etc) are used?  Please advise

**Comment by Robintes** [comment]
Does SV support Midi velocity data? So pressing a key soft and hard makes a difference?
I assume only note value and duration are read when importing a midi song file and no other expression (ASDR etc) are used? Please advise

**Comment by claire-west** [comment]
I doubt it. The closest thing to "velocity" in SynthV is the Loudness parameter, but that isn't quite the same concept. Vocals don't adhere to the same attack/sustain/release pattern that applies to most MIDI-based instruments, so it would probably cause undesirable results if it did.

You can easily verify by recording a sequence and checking the Loudness parameter.

**Comment by Robintes** [comment]
Yes Claire, I tried this with my keyboard controller, recording a midi track and no effect on the notes recorded other than note pitch (ie number) and length. No other input accepted eg pitch and mod wheel.
I'll post a question on the board for general discussion on midi implementation. I'm not sufficiently fluent in midi workings
Food for thought here IMHO

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
