### ISSUE TITLE
Provide Chinese translation

### ISSUE THREAD

**Issue by Blathroat** [claire-west/svstudio-manual#24]
Hello!
This document provides a comprehensive introduction to Synthesizer V.And there's a lot of people in China use SV and need a detailed documentation.So I can provide Chinese translation for free.If there is any need, please contact me at blathroat@outlook.com.

**Comment by claire-west** [comment]
Hello, thank you for the offer!

I have created a new repository for this at https://github.com/claire-west/svstudio-manual-zh. When new commits are pushed to the repository, the [GitHub Actions](https://github.com/claire-west/svstudio-manual-zh/actions) will update the live site at https://zh.synthv.info/. [Offline versions](https://github.com/claire-west/svstudio-manual-zh/releases/tag/latest) will be generated and released automatically at the same time.

You will mainly only need to change text in the various .md files in the docs folder, but there is also some text in the main mkdocs.yml file. If you plan to change screenshots, the images are all in the docs/img folder, and ones with boxes or overlays are also saved in layer-separated PDN format to be edited with [paint.net](https://www.getpaint.net/) (so you can just change the image under the red boxes without having to redraw all the boxes, if that's easier for you). I'll also add a language-switcher to the top of the English site so people can find the translated version (this has already been added to the Chinese version at https://zh.synthv.info/).

You can find all the documentation about Material for MkDocs here: https://squidfunk.github.io/mkdocs-material/.

I'll give your account write permissions for the repository, so you can change files as needed.

I will not have access to my computer for most of the next week (July 31 to approximatey Aug 4/5, perhaps longer), so my ability to assist with issues may be limited, but still feel free to reach out if you need help.
