### ISSUE TITLE
[Voice Panel] Possible Pro-only or upcoming feature - visualise parameters during playback

### ISSUE THREAD

**Issue by Susko3** [claire-west/svstudio-manual#3]
**Describe the problem**

In https://youtu.be/6kzGgaTz3n8?t=107 Dreamtonics showed that using parameters will show a visualisation in the voice panel (during playback).
I've tested and this is not available in the Basic version. So it's either a Pro-only or upcoming feature.

![gif](https://user-images.githubusercontent.com/16479013/216605336-7ab922de-1bd1-42e4-8d2b-6f9e86fde019.gif)

This is not mentioned in https://manual.synthv.info/advanced/side-panels, where I would expect this kind of thing to be mentioned.

**Additional context**

This could also be mentioned in https://manual.synthv.info/parameters/editing-parameters/#base-values.

**Comment by claire-west** [comment]
Looks like a new visualization feature, good catch! Interested to see if we get any other editor improvements with the update.
